### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by dkvasani** [QoboLtd/cakephp-survey#64]
I have tried in cakephp-3.6,3.5,3.7 

All the version gives below errors.

Can you please help us for that
`composer require qobo/cakephp-survey`
  Problem 1
    - qobo/cakephp-utils v12.0.0 requires burzum/cakephp-file-storage dev-branch-2.0 -> no matching package found.
    - qobo/cakephp-survey v4.0.0 requires qobo/cakephp-utils ^12.0 -> satisfiable by qobo/cakephp-utils[v12.0.0].
    - Installation request for qobo/cakephp-survey ^4.0 -> satisfiable by qobo/cakephp-survey[v4.0.0].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.

**Comment by mamchenkov** [comment]
@dkvasani ,

this is because of a temporary issue we have with some third-party dependencies.  Try adding:

```
"minimum-stability": "dev"
```

to your `composer.json`.  This should fix it.

**Comment by dkvasani** [comment]
I have tried with following way.

`"require-dev": {
        "cakephp/bake": "^1.9.0",
        "cakephp/cakephp-codesniffer": "^3.0",
        "cakephp/debug_kit": "^3.17.0",
        "josegonzalez/dotenv": "3.*",
        "phpunit/phpunit": "^5|^6",
        "psy/psysh": "@stable",
        "qobo/cakephp-survey" : "@dev"
    },
"minimum-stability": "dev",`

Still, I am not able to install it so can you please suggest here.

**Comment by asaliev** [comment]
@dkvasani 

Try the following changes to `composer.json`:

```
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/QoboLtd/cakephp-file-storage.git"
        }
    ],
    "require": {
        // add your packages
        // ...
        "qobo/cakephp-survey": "^4.0"
    },
    "prefer-stable": true,
    "minimum-stability": "dev"
```

**Comment by ibastevan** [comment]
I found the dev branch name in "require" needed to be like "burzum/cakephp-file-storage": "dev-branch-2.0",

**Comment by ibastevan** [comment]
Although i am getting Error: Qobo/Survey.SurveyController could not be found. 
I have installed it on v3.6 cake php. Is this compatible with v3.6? 
I tried to install it on 3.5 but the burzum dev branch 2.0 requires cake 3.6 minimum.
Thanks

**Comment by asaliev** [comment]
@ibastevan can you show the whole exception stack trace?

**Comment by ibastevan** [comment]
I found my problem, i didn't have the correct path! to get to the surveys i had to go to myapp.com/surveys/surveys/
For some reason i thought it would have been myapp.com/surveys/
